/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedIntroductionsRouteImport } from './routes/_authenticated/introductions'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedAthenaRouteImport } from './routes/_authenticated/athena'
import { Route as AuthenticatedProfileReviewRouteImport } from './routes/_authenticated/profile.review'
import { Route as AuthenticatedConnectionsIdRouteImport } from './routes/_authenticated/connections.$id'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntroductionsRoute =
  AuthenticatedIntroductionsRouteImport.update({
    id: '/introductions',
    path: '/introductions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAthenaRoute = AuthenticatedAthenaRouteImport.update({
  id: '/athena',
  path: '/athena',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileReviewRoute =
  AuthenticatedProfileReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedConnectionsIdRoute =
  AuthenticatedConnectionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConnectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/athena': typeof AuthenticatedAthenaRoute
  '/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/introductions': typeof AuthenticatedIntroductionsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/connections/$id': typeof AuthenticatedConnectionsIdRoute
  '/profile/review': typeof AuthenticatedProfileReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/athena': typeof AuthenticatedAthenaRoute
  '/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/introductions': typeof AuthenticatedIntroductionsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/connections/$id': typeof AuthenticatedConnectionsIdRoute
  '/profile/review': typeof AuthenticatedProfileReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/athena': typeof AuthenticatedAthenaRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/introductions': typeof AuthenticatedIntroductionsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/connections/$id': typeof AuthenticatedConnectionsIdRoute
  '/_authenticated/profile/review': typeof AuthenticatedProfileReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/athena'
    | '/connections'
    | '/home'
    | '/introductions'
    | '/onboarding'
    | '/profile'
    | '/connections/$id'
    | '/profile/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/athena'
    | '/connections'
    | '/home'
    | '/introductions'
    | '/onboarding'
    | '/profile'
    | '/connections/$id'
    | '/profile/review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/_authenticated/athena'
    | '/_authenticated/connections'
    | '/_authenticated/home'
    | '/_authenticated/introductions'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/connections/$id'
    | '/_authenticated/profile/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/introductions': {
      id: '/_authenticated/introductions'
      path: '/introductions'
      fullPath: '/introductions'
      preLoaderRoute: typeof AuthenticatedIntroductionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athena': {
      id: '/_authenticated/athena'
      path: '/athena'
      fullPath: '/athena'
      preLoaderRoute: typeof AuthenticatedAthenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/review': {
      id: '/_authenticated/profile/review'
      path: '/review'
      fullPath: '/profile/review'
      preLoaderRoute: typeof AuthenticatedProfileReviewRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/connections/$id': {
      id: '/_authenticated/connections/$id'
      path: '/$id'
      fullPath: '/connections/$id'
      preLoaderRoute: typeof AuthenticatedConnectionsIdRouteImport
      parentRoute: typeof AuthenticatedConnectionsRoute
    }
  }
}

interface AuthenticatedConnectionsRouteChildren {
  AuthenticatedConnectionsIdRoute: typeof AuthenticatedConnectionsIdRoute
}

const AuthenticatedConnectionsRouteChildren: AuthenticatedConnectionsRouteChildren =
  {
    AuthenticatedConnectionsIdRoute: AuthenticatedConnectionsIdRoute,
  }

const AuthenticatedConnectionsRouteWithChildren =
  AuthenticatedConnectionsRoute._addFileChildren(
    AuthenticatedConnectionsRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileReviewRoute: typeof AuthenticatedProfileReviewRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileReviewRoute: AuthenticatedProfileReviewRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAthenaRoute: typeof AuthenticatedAthenaRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIntroductionsRoute: typeof AuthenticatedIntroductionsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAthenaRoute: AuthenticatedAthenaRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIntroductionsRoute: AuthenticatedIntroductionsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
