/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWsEchoRouteImport } from './routes/api/ws-echo'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiRealtimeSessionRouteImport } from './routes/api/realtime-session'
import { Route as ApiRealtimeEducationRouteImport } from './routes/api/realtime-education'
import { Route as ApiLiveReleaseRouteImport } from './routes/api/live-release'
import { Route as ApiLiveDiagnosticRouteImport } from './routes/api/live-diagnostic'
import { Route as ApiLiveCredentialRouteImport } from './routes/api/live-credential'
import { Route as ApiElevenAgentChatRouteImport } from './routes/api/eleven-agent-chat'
import { Route as AuthenticatedUnderstandingRouteImport } from './routes/_authenticated/understanding'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedRevealRouteImport } from './routes/_authenticated/reveal'
import { Route as AuthenticatedQaMatchmakingRouteImport } from './routes/_authenticated/qa-matchmaking'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMembershipRouteImport } from './routes/_authenticated/membership'
import { Route as AuthenticatedIntroductionsRouteImport } from './routes/_authenticated/introductions'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFounderRouteImport } from './routes/_authenticated/founder'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedBetaAccountsRouteImport } from './routes/_authenticated/beta-accounts'
import { Route as AuthenticatedAthenaRouteImport } from './routes/_authenticated/athena'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiSpeechEngineWsRouteImport } from './routes/api/speech-engine/ws'
import { Route as ApiPublicRestoreReconcileRouteImport } from './routes/api/public/restore-reconcile'
import { Route as ApiPublicOpsHeartbeatRouteImport } from './routes/api/public/ops-heartbeat'
import { Route as AuthenticatedProfileReviewRouteImport } from './routes/_authenticated/profile.review'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'
import { Route as AuthenticatedIntroductionsIdRouteImport } from './routes/_authenticated/introductions.$id'
import { Route as AuthenticatedFounderPhotosRouteImport } from './routes/_authenticated/founder.photos'
import { Route as AuthenticatedFounderIntelligenceRouteImport } from './routes/_authenticated/founder.intelligence'
import { Route as AuthenticatedFounderAppealsRouteImport } from './routes/_authenticated/founder.appeals'
import { Route as AuthenticatedConnectionsIdRouteImport } from './routes/_authenticated/connections.$id'
import { Route as AuthenticatedAthenaHistoryRouteImport } from './routes/_authenticated/athena.history'
import { Route as AuthenticatedAccountAppealRouteImport } from './routes/_authenticated/account.appeal'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWsEchoRoute = ApiWsEchoRouteImport.update({
  id: '/api/ws-echo',
  path: '/api/ws-echo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeSessionRoute = ApiRealtimeSessionRouteImport.update({
  id: '/api/realtime-session',
  path: '/api/realtime-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeEducationRoute = ApiRealtimeEducationRouteImport.update({
  id: '/api/realtime-education',
  path: '/api/realtime-education',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveReleaseRoute = ApiLiveReleaseRouteImport.update({
  id: '/api/live-release',
  path: '/api/live-release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveDiagnosticRoute = ApiLiveDiagnosticRouteImport.update({
  id: '/api/live-diagnostic',
  path: '/api/live-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveCredentialRoute = ApiLiveCredentialRouteImport.update({
  id: '/api/live-credential',
  path: '/api/live-credential',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenAgentChatRoute = ApiElevenAgentChatRouteImport.update({
  id: '/api/eleven-agent-chat',
  path: '/api/eleven-agent-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnderstandingRoute =
  AuthenticatedUnderstandingRouteImport.update({
    id: '/understanding',
    path: '/understanding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevealRoute = AuthenticatedRevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQaMatchmakingRoute =
  AuthenticatedQaMatchmakingRouteImport.update({
    id: '/qa-matchmaking',
    path: '/qa-matchmaking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembershipRoute = AuthenticatedMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntroductionsRoute =
  AuthenticatedIntroductionsRouteImport.update({
    id: '/introductions',
    path: '/introductions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFounderRoute = AuthenticatedFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBetaAccountsRoute =
  AuthenticatedBetaAccountsRouteImport.update({
    id: '/beta-accounts',
    path: '/beta-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAthenaRoute = AuthenticatedAthenaRouteImport.update({
  id: '/athena',
  path: '/athena',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSpeechEngineWsRoute = ApiSpeechEngineWsRouteImport.update({
  id: '/api/speech-engine/ws',
  path: '/api/speech-engine/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRestoreReconcileRoute =
  ApiPublicRestoreReconcileRouteImport.update({
    id: '/api/public/restore-reconcile',
    path: '/api/public/restore-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOpsHeartbeatRoute = ApiPublicOpsHeartbeatRouteImport.update({
  id: '/api/public/ops-heartbeat',
  path: '/api/public/ops-heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileReviewRoute =
  AuthenticatedProfileReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMessagesRoute,
} as any)
const AuthenticatedIntroductionsIdRoute =
  AuthenticatedIntroductionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedIntroductionsRoute,
  } as any)
const AuthenticatedFounderPhotosRoute =
  AuthenticatedFounderPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedFounderRoute,
  } as any)
const AuthenticatedFounderIntelligenceRoute =
  AuthenticatedFounderIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedFounderRoute,
  } as any)
const AuthenticatedFounderAppealsRoute =
  AuthenticatedFounderAppealsRouteImport.update({
    id: '/appeals',
    path: '/appeals',
    getParentRoute: () => AuthenticatedFounderRoute,
  } as any)
const AuthenticatedConnectionsIdRoute =
  AuthenticatedConnectionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConnectionsRoute,
  } as any)
const AuthenticatedAthenaHistoryRoute =
  AuthenticatedAthenaHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAthenaRoute,
  } as any)
const AuthenticatedAccountAppealRoute =
  AuthenticatedAccountAppealRouteImport.update({
    id: '/appeal',
    path: '/appeal',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/athena': typeof AuthenticatedAthenaRouteWithChildren
  '/beta-accounts': typeof AuthenticatedBetaAccountsRoute
  '/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRoute
  '/founder': typeof AuthenticatedFounderRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/introductions': typeof AuthenticatedIntroductionsRouteWithChildren
  '/membership': typeof AuthenticatedMembershipRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/moderation': typeof AuthenticatedModerationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/qa-matchmaking': typeof AuthenticatedQaMatchmakingRoute
  '/reveal': typeof AuthenticatedRevealRoute
  '/today': typeof AuthenticatedTodayRoute
  '/understanding': typeof AuthenticatedUnderstandingRoute
  '/api/eleven-agent-chat': typeof ApiElevenAgentChatRoute
  '/api/live-credential': typeof ApiLiveCredentialRoute
  '/api/live-diagnostic': typeof ApiLiveDiagnosticRoute
  '/api/live-release': typeof ApiLiveReleaseRoute
  '/api/realtime-education': typeof ApiRealtimeEducationRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/ws-echo': typeof ApiWsEchoRoute
  '/account/appeal': typeof AuthenticatedAccountAppealRoute
  '/athena/history': typeof AuthenticatedAthenaHistoryRoute
  '/connections/$id': typeof AuthenticatedConnectionsIdRoute
  '/founder/appeals': typeof AuthenticatedFounderAppealsRoute
  '/founder/intelligence': typeof AuthenticatedFounderIntelligenceRoute
  '/founder/photos': typeof AuthenticatedFounderPhotosRoute
  '/introductions/$id': typeof AuthenticatedIntroductionsIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/profile/review': typeof AuthenticatedProfileReviewRoute
  '/api/public/ops-heartbeat': typeof ApiPublicOpsHeartbeatRoute
  '/api/public/restore-reconcile': typeof ApiPublicRestoreReconcileRoute
  '/api/speech-engine/ws': typeof ApiSpeechEngineWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/athena': typeof AuthenticatedAthenaRouteWithChildren
  '/beta-accounts': typeof AuthenticatedBetaAccountsRoute
  '/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRoute
  '/founder': typeof AuthenticatedFounderRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/introductions': typeof AuthenticatedIntroductionsRouteWithChildren
  '/membership': typeof AuthenticatedMembershipRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/moderation': typeof AuthenticatedModerationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/qa-matchmaking': typeof AuthenticatedQaMatchmakingRoute
  '/reveal': typeof AuthenticatedRevealRoute
  '/today': typeof AuthenticatedTodayRoute
  '/understanding': typeof AuthenticatedUnderstandingRoute
  '/api/eleven-agent-chat': typeof ApiElevenAgentChatRoute
  '/api/live-credential': typeof ApiLiveCredentialRoute
  '/api/live-diagnostic': typeof ApiLiveDiagnosticRoute
  '/api/live-release': typeof ApiLiveReleaseRoute
  '/api/realtime-education': typeof ApiRealtimeEducationRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/ws-echo': typeof ApiWsEchoRoute
  '/account/appeal': typeof AuthenticatedAccountAppealRoute
  '/athena/history': typeof AuthenticatedAthenaHistoryRoute
  '/connections/$id': typeof AuthenticatedConnectionsIdRoute
  '/founder/appeals': typeof AuthenticatedFounderAppealsRoute
  '/founder/intelligence': typeof AuthenticatedFounderIntelligenceRoute
  '/founder/photos': typeof AuthenticatedFounderPhotosRoute
  '/introductions/$id': typeof AuthenticatedIntroductionsIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/profile/review': typeof AuthenticatedProfileReviewRoute
  '/api/public/ops-heartbeat': typeof ApiPublicOpsHeartbeatRoute
  '/api/public/restore-reconcile': typeof ApiPublicRestoreReconcileRoute
  '/api/speech-engine/ws': typeof ApiSpeechEngineWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/athena': typeof AuthenticatedAthenaRouteWithChildren
  '/_authenticated/beta-accounts': typeof AuthenticatedBetaAccountsRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/founder': typeof AuthenticatedFounderRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/introductions': typeof AuthenticatedIntroductionsRouteWithChildren
  '/_authenticated/membership': typeof AuthenticatedMembershipRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/qa-matchmaking': typeof AuthenticatedQaMatchmakingRoute
  '/_authenticated/reveal': typeof AuthenticatedRevealRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/understanding': typeof AuthenticatedUnderstandingRoute
  '/api/eleven-agent-chat': typeof ApiElevenAgentChatRoute
  '/api/live-credential': typeof ApiLiveCredentialRoute
  '/api/live-diagnostic': typeof ApiLiveDiagnosticRoute
  '/api/live-release': typeof ApiLiveReleaseRoute
  '/api/realtime-education': typeof ApiRealtimeEducationRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/ws-echo': typeof ApiWsEchoRoute
  '/_authenticated/account/appeal': typeof AuthenticatedAccountAppealRoute
  '/_authenticated/athena/history': typeof AuthenticatedAthenaHistoryRoute
  '/_authenticated/connections/$id': typeof AuthenticatedConnectionsIdRoute
  '/_authenticated/founder/appeals': typeof AuthenticatedFounderAppealsRoute
  '/_authenticated/founder/intelligence': typeof AuthenticatedFounderIntelligenceRoute
  '/_authenticated/founder/photos': typeof AuthenticatedFounderPhotosRoute
  '/_authenticated/introductions/$id': typeof AuthenticatedIntroductionsIdRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/profile/review': typeof AuthenticatedProfileReviewRoute
  '/api/public/ops-heartbeat': typeof ApiPublicOpsHeartbeatRoute
  '/api/public/restore-reconcile': typeof ApiPublicRestoreReconcileRoute
  '/api/speech-engine/ws': typeof ApiSpeechEngineWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/account'
    | '/athena'
    | '/beta-accounts'
    | '/connections'
    | '/conversations'
    | '/founder'
    | '/home'
    | '/introductions'
    | '/membership'
    | '/messages'
    | '/moderation'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/qa-matchmaking'
    | '/reveal'
    | '/today'
    | '/understanding'
    | '/api/eleven-agent-chat'
    | '/api/live-credential'
    | '/api/live-diagnostic'
    | '/api/live-release'
    | '/api/realtime-education'
    | '/api/realtime-session'
    | '/api/stt'
    | '/api/tts'
    | '/api/ws-echo'
    | '/account/appeal'
    | '/athena/history'
    | '/connections/$id'
    | '/founder/appeals'
    | '/founder/intelligence'
    | '/founder/photos'
    | '/introductions/$id'
    | '/messages/$id'
    | '/profile/review'
    | '/api/public/ops-heartbeat'
    | '/api/public/restore-reconcile'
    | '/api/speech-engine/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/account'
    | '/athena'
    | '/beta-accounts'
    | '/connections'
    | '/conversations'
    | '/founder'
    | '/home'
    | '/introductions'
    | '/membership'
    | '/messages'
    | '/moderation'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/qa-matchmaking'
    | '/reveal'
    | '/today'
    | '/understanding'
    | '/api/eleven-agent-chat'
    | '/api/live-credential'
    | '/api/live-diagnostic'
    | '/api/live-release'
    | '/api/realtime-education'
    | '/api/realtime-session'
    | '/api/stt'
    | '/api/tts'
    | '/api/ws-echo'
    | '/account/appeal'
    | '/athena/history'
    | '/connections/$id'
    | '/founder/appeals'
    | '/founder/intelligence'
    | '/founder/photos'
    | '/introductions/$id'
    | '/messages/$id'
    | '/profile/review'
    | '/api/public/ops-heartbeat'
    | '/api/public/restore-reconcile'
    | '/api/speech-engine/ws'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-callback'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/athena'
    | '/_authenticated/beta-accounts'
    | '/_authenticated/connections'
    | '/_authenticated/conversations'
    | '/_authenticated/founder'
    | '/_authenticated/home'
    | '/_authenticated/introductions'
    | '/_authenticated/membership'
    | '/_authenticated/messages'
    | '/_authenticated/moderation'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/qa-matchmaking'
    | '/_authenticated/reveal'
    | '/_authenticated/today'
    | '/_authenticated/understanding'
    | '/api/eleven-agent-chat'
    | '/api/live-credential'
    | '/api/live-diagnostic'
    | '/api/live-release'
    | '/api/realtime-education'
    | '/api/realtime-session'
    | '/api/stt'
    | '/api/tts'
    | '/api/ws-echo'
    | '/_authenticated/account/appeal'
    | '/_authenticated/athena/history'
    | '/_authenticated/connections/$id'
    | '/_authenticated/founder/appeals'
    | '/_authenticated/founder/intelligence'
    | '/_authenticated/founder/photos'
    | '/_authenticated/introductions/$id'
    | '/_authenticated/messages/$id'
    | '/_authenticated/profile/review'
    | '/api/public/ops-heartbeat'
    | '/api/public/restore-reconcile'
    | '/api/speech-engine/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiElevenAgentChatRoute: typeof ApiElevenAgentChatRoute
  ApiLiveCredentialRoute: typeof ApiLiveCredentialRoute
  ApiLiveDiagnosticRoute: typeof ApiLiveDiagnosticRoute
  ApiLiveReleaseRoute: typeof ApiLiveReleaseRoute
  ApiRealtimeEducationRoute: typeof ApiRealtimeEducationRoute
  ApiRealtimeSessionRoute: typeof ApiRealtimeSessionRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiWsEchoRoute: typeof ApiWsEchoRoute
  ApiPublicOpsHeartbeatRoute: typeof ApiPublicOpsHeartbeatRoute
  ApiPublicRestoreReconcileRoute: typeof ApiPublicRestoreReconcileRoute
  ApiSpeechEngineWsRoute: typeof ApiSpeechEngineWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ws-echo': {
      id: '/api/ws-echo'
      path: '/api/ws-echo'
      fullPath: '/api/ws-echo'
      preLoaderRoute: typeof ApiWsEchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime-session': {
      id: '/api/realtime-session'
      path: '/api/realtime-session'
      fullPath: '/api/realtime-session'
      preLoaderRoute: typeof ApiRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime-education': {
      id: '/api/realtime-education'
      path: '/api/realtime-education'
      fullPath: '/api/realtime-education'
      preLoaderRoute: typeof ApiRealtimeEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-release': {
      id: '/api/live-release'
      path: '/api/live-release'
      fullPath: '/api/live-release'
      preLoaderRoute: typeof ApiLiveReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-diagnostic': {
      id: '/api/live-diagnostic'
      path: '/api/live-diagnostic'
      fullPath: '/api/live-diagnostic'
      preLoaderRoute: typeof ApiLiveDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-credential': {
      id: '/api/live-credential'
      path: '/api/live-credential'
      fullPath: '/api/live-credential'
      preLoaderRoute: typeof ApiLiveCredentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eleven-agent-chat': {
      id: '/api/eleven-agent-chat'
      path: '/api/eleven-agent-chat'
      fullPath: '/api/eleven-agent-chat'
      preLoaderRoute: typeof ApiElevenAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/understanding': {
      id: '/_authenticated/understanding'
      path: '/understanding'
      fullPath: '/understanding'
      preLoaderRoute: typeof AuthenticatedUnderstandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reveal': {
      id: '/_authenticated/reveal'
      path: '/reveal'
      fullPath: '/reveal'
      preLoaderRoute: typeof AuthenticatedRevealRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa-matchmaking': {
      id: '/_authenticated/qa-matchmaking'
      path: '/qa-matchmaking'
      fullPath: '/qa-matchmaking'
      preLoaderRoute: typeof AuthenticatedQaMatchmakingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membership': {
      id: '/_authenticated/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AuthenticatedMembershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/introductions': {
      id: '/_authenticated/introductions'
      path: '/introductions'
      fullPath: '/introductions'
      preLoaderRoute: typeof AuthenticatedIntroductionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/founder': {
      id: '/_authenticated/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof AuthenticatedFounderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beta-accounts': {
      id: '/_authenticated/beta-accounts'
      path: '/beta-accounts'
      fullPath: '/beta-accounts'
      preLoaderRoute: typeof AuthenticatedBetaAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athena': {
      id: '/_authenticated/athena'
      path: '/athena'
      fullPath: '/athena'
      preLoaderRoute: typeof AuthenticatedAthenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/speech-engine/ws': {
      id: '/api/speech-engine/ws'
      path: '/api/speech-engine/ws'
      fullPath: '/api/speech-engine/ws'
      preLoaderRoute: typeof ApiSpeechEngineWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/restore-reconcile': {
      id: '/api/public/restore-reconcile'
      path: '/api/public/restore-reconcile'
      fullPath: '/api/public/restore-reconcile'
      preLoaderRoute: typeof ApiPublicRestoreReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ops-heartbeat': {
      id: '/api/public/ops-heartbeat'
      path: '/api/public/ops-heartbeat'
      fullPath: '/api/public/ops-heartbeat'
      preLoaderRoute: typeof ApiPublicOpsHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/review': {
      id: '/_authenticated/profile/review'
      path: '/review'
      fullPath: '/profile/review'
      preLoaderRoute: typeof AuthenticatedProfileReviewRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/introductions/$id': {
      id: '/_authenticated/introductions/$id'
      path: '/$id'
      fullPath: '/introductions/$id'
      preLoaderRoute: typeof AuthenticatedIntroductionsIdRouteImport
      parentRoute: typeof AuthenticatedIntroductionsRoute
    }
    '/_authenticated/founder/photos': {
      id: '/_authenticated/founder/photos'
      path: '/photos'
      fullPath: '/founder/photos'
      preLoaderRoute: typeof AuthenticatedFounderPhotosRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/_authenticated/founder/intelligence': {
      id: '/_authenticated/founder/intelligence'
      path: '/intelligence'
      fullPath: '/founder/intelligence'
      preLoaderRoute: typeof AuthenticatedFounderIntelligenceRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/_authenticated/founder/appeals': {
      id: '/_authenticated/founder/appeals'
      path: '/appeals'
      fullPath: '/founder/appeals'
      preLoaderRoute: typeof AuthenticatedFounderAppealsRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/_authenticated/connections/$id': {
      id: '/_authenticated/connections/$id'
      path: '/$id'
      fullPath: '/connections/$id'
      preLoaderRoute: typeof AuthenticatedConnectionsIdRouteImport
      parentRoute: typeof AuthenticatedConnectionsRoute
    }
    '/_authenticated/athena/history': {
      id: '/_authenticated/athena/history'
      path: '/history'
      fullPath: '/athena/history'
      preLoaderRoute: typeof AuthenticatedAthenaHistoryRouteImport
      parentRoute: typeof AuthenticatedAthenaRoute
    }
    '/_authenticated/account/appeal': {
      id: '/_authenticated/account/appeal'
      path: '/appeal'
      fullPath: '/account/appeal'
      preLoaderRoute: typeof AuthenticatedAccountAppealRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountAppealRoute: typeof AuthenticatedAccountAppealRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountAppealRoute: AuthenticatedAccountAppealRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAthenaRouteChildren {
  AuthenticatedAthenaHistoryRoute: typeof AuthenticatedAthenaHistoryRoute
}

const AuthenticatedAthenaRouteChildren: AuthenticatedAthenaRouteChildren = {
  AuthenticatedAthenaHistoryRoute: AuthenticatedAthenaHistoryRoute,
}

const AuthenticatedAthenaRouteWithChildren =
  AuthenticatedAthenaRoute._addFileChildren(AuthenticatedAthenaRouteChildren)

interface AuthenticatedConnectionsRouteChildren {
  AuthenticatedConnectionsIdRoute: typeof AuthenticatedConnectionsIdRoute
}

const AuthenticatedConnectionsRouteChildren: AuthenticatedConnectionsRouteChildren =
  {
    AuthenticatedConnectionsIdRoute: AuthenticatedConnectionsIdRoute,
  }

const AuthenticatedConnectionsRouteWithChildren =
  AuthenticatedConnectionsRoute._addFileChildren(
    AuthenticatedConnectionsRouteChildren,
  )

interface AuthenticatedFounderRouteChildren {
  AuthenticatedFounderAppealsRoute: typeof AuthenticatedFounderAppealsRoute
  AuthenticatedFounderIntelligenceRoute: typeof AuthenticatedFounderIntelligenceRoute
  AuthenticatedFounderPhotosRoute: typeof AuthenticatedFounderPhotosRoute
}

const AuthenticatedFounderRouteChildren: AuthenticatedFounderRouteChildren = {
  AuthenticatedFounderAppealsRoute: AuthenticatedFounderAppealsRoute,
  AuthenticatedFounderIntelligenceRoute: AuthenticatedFounderIntelligenceRoute,
  AuthenticatedFounderPhotosRoute: AuthenticatedFounderPhotosRoute,
}

const AuthenticatedFounderRouteWithChildren =
  AuthenticatedFounderRoute._addFileChildren(AuthenticatedFounderRouteChildren)

interface AuthenticatedIntroductionsRouteChildren {
  AuthenticatedIntroductionsIdRoute: typeof AuthenticatedIntroductionsIdRoute
}

const AuthenticatedIntroductionsRouteChildren: AuthenticatedIntroductionsRouteChildren =
  {
    AuthenticatedIntroductionsIdRoute: AuthenticatedIntroductionsIdRoute,
  }

const AuthenticatedIntroductionsRouteWithChildren =
  AuthenticatedIntroductionsRoute._addFileChildren(
    AuthenticatedIntroductionsRouteChildren,
  )

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileReviewRoute: typeof AuthenticatedProfileReviewRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileReviewRoute: AuthenticatedProfileReviewRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAthenaRoute: typeof AuthenticatedAthenaRouteWithChildren
  AuthenticatedBetaAccountsRoute: typeof AuthenticatedBetaAccountsRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRouteWithChildren
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedFounderRoute: typeof AuthenticatedFounderRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIntroductionsRoute: typeof AuthenticatedIntroductionsRouteWithChildren
  AuthenticatedMembershipRoute: typeof AuthenticatedMembershipRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedQaMatchmakingRoute: typeof AuthenticatedQaMatchmakingRoute
  AuthenticatedRevealRoute: typeof AuthenticatedRevealRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedUnderstandingRoute: typeof AuthenticatedUnderstandingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAthenaRoute: AuthenticatedAthenaRouteWithChildren,
  AuthenticatedBetaAccountsRoute: AuthenticatedBetaAccountsRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRouteWithChildren,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedFounderRoute: AuthenticatedFounderRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIntroductionsRoute: AuthenticatedIntroductionsRouteWithChildren,
  AuthenticatedMembershipRoute: AuthenticatedMembershipRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedQaMatchmakingRoute: AuthenticatedQaMatchmakingRoute,
  AuthenticatedRevealRoute: AuthenticatedRevealRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedUnderstandingRoute: AuthenticatedUnderstandingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiElevenAgentChatRoute: ApiElevenAgentChatRoute,
  ApiLiveCredentialRoute: ApiLiveCredentialRoute,
  ApiLiveDiagnosticRoute: ApiLiveDiagnosticRoute,
  ApiLiveReleaseRoute: ApiLiveReleaseRoute,
  ApiRealtimeEducationRoute: ApiRealtimeEducationRoute,
  ApiRealtimeSessionRoute: ApiRealtimeSessionRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiWsEchoRoute: ApiWsEchoRoute,
  ApiPublicOpsHeartbeatRoute: ApiPublicOpsHeartbeatRoute,
  ApiPublicRestoreReconcileRoute: ApiPublicRestoreReconcileRoute,
  ApiSpeechEngineWsRoute: ApiSpeechEngineWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
