/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as AuthenticatedUnderstandingRouteImport } from './routes/_authenticated/understanding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedIntroductionsRouteImport } from './routes/_authenticated/introductions'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFounderRouteImport } from './routes/_authenticated/founder'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedAthenaRouteImport } from './routes/_authenticated/athena'
import { Route as ApiPublicRestoreReconcileRouteImport } from './routes/api/public/restore-reconcile'
import { Route as ApiPublicOpsHeartbeatRouteImport } from './routes/api/public/ops-heartbeat'
import { Route as AuthenticatedProfileReviewRouteImport } from './routes/_authenticated/profile.review'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'
import { Route as AuthenticatedIntroductionsIdRouteImport } from './routes/_authenticated/introductions.$id'
import { Route as AuthenticatedConnectionsIdRouteImport } from './routes/_authenticated/connections.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnderstandingRoute =
  AuthenticatedUnderstandingRouteImport.update({
    id: '/understanding',
    path: '/understanding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntroductionsRoute =
  AuthenticatedIntroductionsRouteImport.update({
    id: '/introductions',
    path: '/introductions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFounderRoute = AuthenticatedFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAthenaRoute = AuthenticatedAthenaRouteImport.update({
  id: '/athena',
  path: '/athena',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRestoreReconcileRoute =
  ApiPublicRestoreReconcileRouteImport.update({
    id: '/api/public/restore-reconcile',
    path: '/api/public/restore-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOpsHeartbeatRoute = ApiPublicOpsHeartbeatRouteImport.update({
  id: '/api/public/ops-heartbeat',
  path: '/api/public/ops-heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileReviewRoute =
  AuthenticatedProfileReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMessagesRoute,
} as any)
const AuthenticatedIntroductionsIdRoute =
  AuthenticatedIntroductionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedIntroductionsRoute,
  } as any)
const AuthenticatedConnectionsIdRoute =
  AuthenticatedConnectionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConnectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/athena': typeof AuthenticatedAthenaRoute
  '/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRoute
  '/founder': typeof AuthenticatedFounderRoute
  '/home': typeof AuthenticatedHomeRoute
  '/introductions': typeof AuthenticatedIntroductionsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/moderation': typeof AuthenticatedModerationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/understanding': typeof AuthenticatedUnderstandingRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/connections/$id': typeof AuthenticatedConnectionsIdRoute
  '/introductions/$id': typeof AuthenticatedIntroductionsIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/profile/review': typeof AuthenticatedProfileReviewRoute
  '/api/public/ops-heartbeat': typeof ApiPublicOpsHeartbeatRoute
  '/api/public/restore-reconcile': typeof ApiPublicRestoreReconcileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/athena': typeof AuthenticatedAthenaRoute
  '/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRoute
  '/founder': typeof AuthenticatedFounderRoute
  '/home': typeof AuthenticatedHomeRoute
  '/introductions': typeof AuthenticatedIntroductionsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/moderation': typeof AuthenticatedModerationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/understanding': typeof AuthenticatedUnderstandingRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/connections/$id': typeof AuthenticatedConnectionsIdRoute
  '/introductions/$id': typeof AuthenticatedIntroductionsIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/profile/review': typeof AuthenticatedProfileReviewRoute
  '/api/public/ops-heartbeat': typeof ApiPublicOpsHeartbeatRoute
  '/api/public/restore-reconcile': typeof ApiPublicRestoreReconcileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/athena': typeof AuthenticatedAthenaRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/founder': typeof AuthenticatedFounderRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/introductions': typeof AuthenticatedIntroductionsRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/understanding': typeof AuthenticatedUnderstandingRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/connections/$id': typeof AuthenticatedConnectionsIdRoute
  '/_authenticated/introductions/$id': typeof AuthenticatedIntroductionsIdRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/profile/review': typeof AuthenticatedProfileReviewRoute
  '/api/public/ops-heartbeat': typeof ApiPublicOpsHeartbeatRoute
  '/api/public/restore-reconcile': typeof ApiPublicRestoreReconcileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/athena'
    | '/connections'
    | '/conversations'
    | '/founder'
    | '/home'
    | '/introductions'
    | '/messages'
    | '/moderation'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/understanding'
    | '/api/stt'
    | '/api/tts'
    | '/connections/$id'
    | '/introductions/$id'
    | '/messages/$id'
    | '/profile/review'
    | '/api/public/ops-heartbeat'
    | '/api/public/restore-reconcile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/athena'
    | '/connections'
    | '/conversations'
    | '/founder'
    | '/home'
    | '/introductions'
    | '/messages'
    | '/moderation'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/understanding'
    | '/api/stt'
    | '/api/tts'
    | '/connections/$id'
    | '/introductions/$id'
    | '/messages/$id'
    | '/profile/review'
    | '/api/public/ops-heartbeat'
    | '/api/public/restore-reconcile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/athena'
    | '/_authenticated/connections'
    | '/_authenticated/conversations'
    | '/_authenticated/founder'
    | '/_authenticated/home'
    | '/_authenticated/introductions'
    | '/_authenticated/messages'
    | '/_authenticated/moderation'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/understanding'
    | '/api/stt'
    | '/api/tts'
    | '/_authenticated/connections/$id'
    | '/_authenticated/introductions/$id'
    | '/_authenticated/messages/$id'
    | '/_authenticated/profile/review'
    | '/api/public/ops-heartbeat'
    | '/api/public/restore-reconcile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicOpsHeartbeatRoute: typeof ApiPublicOpsHeartbeatRoute
  ApiPublicRestoreReconcileRoute: typeof ApiPublicRestoreReconcileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/understanding': {
      id: '/_authenticated/understanding'
      path: '/understanding'
      fullPath: '/understanding'
      preLoaderRoute: typeof AuthenticatedUnderstandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/introductions': {
      id: '/_authenticated/introductions'
      path: '/introductions'
      fullPath: '/introductions'
      preLoaderRoute: typeof AuthenticatedIntroductionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/founder': {
      id: '/_authenticated/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof AuthenticatedFounderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athena': {
      id: '/_authenticated/athena'
      path: '/athena'
      fullPath: '/athena'
      preLoaderRoute: typeof AuthenticatedAthenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/restore-reconcile': {
      id: '/api/public/restore-reconcile'
      path: '/api/public/restore-reconcile'
      fullPath: '/api/public/restore-reconcile'
      preLoaderRoute: typeof ApiPublicRestoreReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ops-heartbeat': {
      id: '/api/public/ops-heartbeat'
      path: '/api/public/ops-heartbeat'
      fullPath: '/api/public/ops-heartbeat'
      preLoaderRoute: typeof ApiPublicOpsHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/review': {
      id: '/_authenticated/profile/review'
      path: '/review'
      fullPath: '/profile/review'
      preLoaderRoute: typeof AuthenticatedProfileReviewRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/introductions/$id': {
      id: '/_authenticated/introductions/$id'
      path: '/$id'
      fullPath: '/introductions/$id'
      preLoaderRoute: typeof AuthenticatedIntroductionsIdRouteImport
      parentRoute: typeof AuthenticatedIntroductionsRoute
    }
    '/_authenticated/connections/$id': {
      id: '/_authenticated/connections/$id'
      path: '/$id'
      fullPath: '/connections/$id'
      preLoaderRoute: typeof AuthenticatedConnectionsIdRouteImport
      parentRoute: typeof AuthenticatedConnectionsRoute
    }
  }
}

interface AuthenticatedConnectionsRouteChildren {
  AuthenticatedConnectionsIdRoute: typeof AuthenticatedConnectionsIdRoute
}

const AuthenticatedConnectionsRouteChildren: AuthenticatedConnectionsRouteChildren =
  {
    AuthenticatedConnectionsIdRoute: AuthenticatedConnectionsIdRoute,
  }

const AuthenticatedConnectionsRouteWithChildren =
  AuthenticatedConnectionsRoute._addFileChildren(
    AuthenticatedConnectionsRouteChildren,
  )

interface AuthenticatedIntroductionsRouteChildren {
  AuthenticatedIntroductionsIdRoute: typeof AuthenticatedIntroductionsIdRoute
}

const AuthenticatedIntroductionsRouteChildren: AuthenticatedIntroductionsRouteChildren =
  {
    AuthenticatedIntroductionsIdRoute: AuthenticatedIntroductionsIdRoute,
  }

const AuthenticatedIntroductionsRouteWithChildren =
  AuthenticatedIntroductionsRoute._addFileChildren(
    AuthenticatedIntroductionsRouteChildren,
  )

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileReviewRoute: typeof AuthenticatedProfileReviewRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileReviewRoute: AuthenticatedProfileReviewRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAthenaRoute: typeof AuthenticatedAthenaRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRouteWithChildren
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedFounderRoute: typeof AuthenticatedFounderRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIntroductionsRoute: typeof AuthenticatedIntroductionsRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedUnderstandingRoute: typeof AuthenticatedUnderstandingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAthenaRoute: AuthenticatedAthenaRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRouteWithChildren,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedFounderRoute: AuthenticatedFounderRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIntroductionsRoute: AuthenticatedIntroductionsRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedUnderstandingRoute: AuthenticatedUnderstandingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicOpsHeartbeatRoute: ApiPublicOpsHeartbeatRoute,
  ApiPublicRestoreReconcileRoute: ApiPublicRestoreReconcileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
